server:
  port: 8084

spring:
  application:
    name: api-gateway
    
# gateway config
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/users/**

      - id: hotel-service
        uri: lb://hotel-service
        predicates:
        - Path=/hotels/**

      - id: rating-service
        uri: lb://rating-service
        predicates:
        - Path=/ratings/**

# Eureka Config
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Okta Config
okta:
  oauth2:
    issuer: https://dev-52786026.okta.com/oauth2/default
    audience: api://default
    client-id: 0oab12nv73lSfbnwy5d7
    client-secret: 4x_BbQBVUnMElihzJzxn4bCPT68IlOgFYANHclDY73vkKYOlpr3-YDV-EdvrmXwF
    scopes: openid, profile, email, offline_access

